### PR TITLE
Added Fairy_Comment_Generator Extension

### PR DESCRIPTION
**Pull request by devrishikm**
It's throwing some error while running the extension but the extension is totally working fine.

### CODE REVIEW

**Comment by CodesbyUnnati** [comment]
There are some errors.
image

**Comment by devrishikm** [comment]
I was not able to resolve those errors but the extension is working perfectly fine.

**Comment by CodesbyUnnati** [comment]
> I was not able to resolve those errors but the extension is working perfectly fine.

It's not working for me..nothing happens when I click the extension.

**Comment by devrishikm** [comment]
I have updated the code.
when you click on generate a fairy comment it should generate a comment.
As I have mentioned earlier I am not able to fix the error named math.random but the extension works perfectly fine.
Thank you

**Pull request merged**
