### PR TITLE
Music player chrome extension

### PR DESCRIPTION
**Pull request by abhishek213-alb**

### CODE REVIEW

**Comment by abhishek213-alb** [comment]
@CodesbyUnnati Please review and merge

**Comment by abhishek213-alb** [comment]
@CodesbyUnnati

**Comment by CodesbyUnnati** [comment]
I think you haven't uploaded ur files inside a folder. Please make a separate folder and push the files.
image

**Comment by CodesbyUnnati** [comment]
This is having conflicts, please resolve them or make a new PR.

**Comment by abhishek213-alb** [comment]
@CodesbyUnnati I have made a new pr

**Pull request closed without merging**
