### PR TITLE
Create readme.md

### PR DESCRIPTION
**Pull request by gantavyamalviya**

### CODE REVIEW

**Comment by gantavyamalviya** [comment]
i have created a folder, pls merge it so that i can upload other files of that folder asap

**Comment by CodesbyUnnati** [comment]
Please read the instructions on how to make the PR. You have committed readme.md file.
You have to create a folder of ur extension and then make a PR for that.

**Comment by gantavyamalviya** [comment]
I have created a folder, including readme.md

**Comment by CodesbyUnnati** [comment]
Upload all your code as a single PR. This cannot be merged.

**Pull request closed without merging**
