### PR TITLE
chore: add covid stats extension by ashiishme

### PR DESCRIPTION
**Pull request by ashiishme**

### CODE REVIEW

**Review by pratikbutani — APPROVED** [review]

**Comment by ashiishme** [comment]
@pratikbutani  Just for your information, this repo is not eligible for Hacktoberfest 2021. Can you please check and see if this can be fixed?

**Comment by ashiishme** [comment]
Update: It's showing as valid now.

**Comment by ashiishme** [comment]
Can you merge this please?

**Comment by CodesbyUnnati** [comment]
I cannot run it by uploading the folder on the extensions. Please share the way to run it.

**Comment by ashiishme** [comment]
To run this project, you need to first build the files. The extension is written using TypeScript and React.

To run this extension:

** Make sure you have Node & Yarn installed **

Inside the project root, install all the dependencies with yarn:
> yarn

Once everything is installed properly, run the build command:
> yarn build

After the successful build, load unpacked extension and test it.

You can also check the Readme file provided with this PR to learn more about the project and the local setup guide.

**Comment by CodesbyUnnati** [comment]
Thanks for giving such a valuable contribution 💯 
Merged.
Do star the Repo⭐

**Pull request merged**
