### PR TITLE
Birds added

### PR DESCRIPTION
**Pull request by SachinRaghuvanshi2003**
Hope you like it. Thanks for your support :)

### CODE REVIEW

**Comment by CodesbyUnnati** [comment]
Can u pl check once, it shows like this->
image

**Comment by SachinRaghuvanshi2003** [comment]
yes it is.
outputbirds

**Comment by SachinRaghuvanshi2003** [comment]
it is working absolutely fine.. can you check?

**Comment by CodesbyUnnati** [comment]
Please remove the "center" property, as it the picture is appearing on center of the screen, but the size is 500px by 500px, so remove the center property and add the logo to the extension. Else it is working fine.

**Comment by CodesbyUnnati** [comment]
> yes it is. outputbirds

this is visible only when it is full screen, otherwise because of the center property, it is way too big, Please remove center property.

**Comment by SachinRaghuvanshi2003** [comment]
I have done the required changes. Please check.

**Comment by SachinRaghuvanshi2003** [comment]
Can you please merge it, it'll be my last pr as to achieve my goal. I'll be highly grateful

**Pull request merged**
