### PR TITLE
Siteblocker Extension Added and Random Inspirational Quote Extension Added 

### PR DESCRIPTION
**Pull request by sauravpathakofficial**
This is Extension that blocks sites we want . Like the sites that you  don't want your device to acesss . Example try Zedo.com

### CODE REVIEW

**Comment by sauravpathakofficial** [comment]
please review

**Comment by CodesbyUnnati** [comment]
Can u please tell how it works? I loaded the extension and clicked on it when add appeared, but nothing happened.
WhatsApp Image 2021-10-01 at 10 03 52 PM

**Comment by sauravpathakofficial** [comment]
Screenshot 2021-10-01 231120

**Comment by sauravpathakofficial** [comment]
This Extension  blocks sites we want . Like the sites that you don't want your device to acesss . Example try Zedo.com

**Review by sauravpathakofficial — COMMENTED** [review]
Extension gives a new inspiration quotes

**Pull request merged**
